version: "3"

services:
  web:
    image: nginx:alpine
    container_name: vow_web
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www

  fpm:
    build: .
    image: digitalocean.com/php
    container_name: vow_fpm
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8
    container_name: vow_mysql
    restart: unless-stopped
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../mysql.cnf:/etc/mysql/conf.d/custom.cnf
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: vow
      MYSQL_USER: vow_admin
      MYSQL_PASSWORD: p@ssw0rd

  redis:
    image: redis:alpine
    container_name: vow_redis
    restart: unless-stopped
    expose:
      - 6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ../data/redis:/var/lib/redis


networks:
  default:
    external:
      name: rocket-net
